### ISSUE TITLE
Create Script to Move Tory Left and Right

### ISSUE THREAD

**Issue by wolffcaleb** [pvcraven/2018_cis390ag#71]
Create Script to move Tory left and right.
Tory should move Left and Right on the "Horizontal" axis.

**Comment by NateHawk85** [comment]
I will also add a script for jumping functionality.

**Comment by keeganlamparek** [comment]
Also add a Flip() method on the Player script to flip around the player if moving right or left. Like we did on Assignment 7.

**Comment by braedeningersoll** [comment]
Line 43 uses vector3 while line 58 uses vector2. I imagine we only need to use vector2 since we have no need to use the z value.

**Comment by NateHawk85** [comment]
The documentation says that Unity's transform.localScale is a Vector3 variable. On line 43, since we're setting a new variable equal to the current transform.localScale, having a Vector3 there will store all the information that the localScale holds. The documentation is [here](https://docs.unity3d.com/ScriptReference/Rigidbody2D-velocity.html).

On the other hand, on line 58, rigidbody2D.velocity is a variable of type Vector2. The documentation is [here](https://docs.unity3d.com/ScriptReference/Rigidbody2D-velocity.html).

I don't have enough experience with Unity to know which is more appropriate to use. I was creating variables according to the documentation, but it is possible to use Vector2 instead of Vector3 on line 43 since I assume Vector2 is a child of Vector3. I assumed Vector3 was the correct class to use since they used it in the tutorial we watched, but I could definitely be wrong.
