### ISSUE TITLE
Overword?

### ISSUE THREAD

**Issue by rhovey15** [pvcraven/2018_cis390ag#73]
I think we need to decide if we are making an overworld map (moving from level to level) or have the levels lead from one to another.

**Comment by wolffcaleb** [comment]
I'm assuming you mean doing for example six separate scenes (tutorial and five levels) as opposed to a single, consistently scrolling level with what would be, more or less, checkpoints?

If so, I agree and I believe we should do six separate scenes so that we have more bite-sized sections to works on. Then at the end we just call something like this...`void LoadNextLevel(String sceneName){ SceneManager.LoadScene(sceneName);}`

**Comment by pvcraven** [comment]
Separate levels, not all one map.
